name: fitness_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  device_preview: ^1.1.0
  confetti: ^0.7.0
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.1
  grouped_list: ^5.1.2
  camera: ^0.11.1
  cloud_functions: ^5.4.0
  image_picker: ^1.1.2
  shared_preferences: ^2.5.3
  # Firebase dependencies are removed for web compatibility

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:                    # Only ONE flutter: section should exist
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/